name: 'Update Extension Registry Version'
description: 'Add a new version to a module in the k6 extension registry via centralized workflow'
author: 'Grafana Labs'

inputs:
  module:
    description: 'The module name to update (e.g., github.com/grafana/xk6-sql)'
    required: true
  version:
    description: 'The version to add (e.g., v1.0.6)'
    required: true
  token:
    description: 'GitHub token with permissions to trigger workflows'
    required: true
  repository-url:
    description: 'URL of the source repository (optional, used to validate if the change is trusted)'
    required: false
  release-url:
    description: 'URL of the release (optional, used for PR context)'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Trigger registry update workflow
      uses: peter-evans/repository-dispatch@v3
      with:
        token: ${{ inputs.token }}
        repository: grafana/k6-extension-registry
        event-type: extension_version_update
        client-payload: |
          {
            "module": "${{ inputs.module }}",
            "version": "${{ inputs.version }}",
            "repository_url": "${{ inputs.repository-url }}",
            "release_url": "${{ inputs.release-url }}"
          }

branding:
  icon: 'package'
  color: 'orange'