on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      actions: read
    outputs:
      new_versions: ${{ steps.check.outputs.new_versions }}
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          persist-credentials: false

      - name: setup
        uses: ./.github/actions/k6registry_setup

      - name: check
        run: >
          ./check-new-versions.sh --lint --verbose

